[global] #Global paramters
run_path = '/home/energy/mahpe/Published_code/autocPaiNN/Example' #Where you want to run the code. The Directoru will be created in "pq_submit.py"
random_seed = 3407 #A random seed used for the ML model. This is used for the whole workflow.
max_iteration = 10 #Maximum number of itertaion to run the workflow. The worklow can be stopped earlier

### 1) Train step ###
[train] #Main parameters
cutoff = 4.0 
val_ratio = 0.1
node_size = 64 
num_interactions = 4
output_dir = 'model_output' #The folder name for which the MLP will be saved at every itertaion except if you train ensembles
dataset = '/home/energy/mahpe/Published_code/polyanion_cathode_dataset/Combined.xyz' #CHANGE to correct path. Training set datapath. It will be steadily increasing
max_steps = 1500000 #Maxium number of epochs
batch_size = 20 #Number of strutcures in each batch
initial_lr = 0.0001
forces_weight = 0.98 #The energy wieght is 1-force_weight
charge_weight = 0.1 #Bader charge and magmom wieght
stress_weight = 1000
log_interval = 2000 #The number of which validation will be performed

plateau_scheduler = true #Change the learning rate according to the change in training loss
normalization = true #Normalize the energy 
atomwise_normalization = true #Normalize it per atom or per sample
stop_patience = 1000 #When to stop the training when the same loss have been seen repeatedly 

compute_forces = true #Train with forces
compute_stress = true #Train with stess
compute_magmom=true #Train with magnetic moments
compute_bader_charge=false #Train with Bader charge. Check if your data follows the bader attachment in "bader_attach.py"

stop_after_train = false #IMPORTANT. This parameters lets you stop the workflow after it has performed a last MLP training
load_prev_iter_model = true #Load previose models from earlier itertaions

[train.ensemble] #Ensemble parameters. Each dictionary represent another model with new parameters. You need at least to train two different model in the current verion of auto-cPaiNN
128_node_4_layer = {node_size = 128, num_interactions = 4}
256_node_4_layer = {node_size = 256, num_interactions = 4}
512_node_4_layer = {node_size = 512, num_interactions = 4}

### 2) Simulate step ###
[simulate.MD] #Main molecular dynamics(MD) paramaters. Can be updated by each system
time_step = 1 
temperature = 1000
device = 'cpu'
start_indice = -1 #Uses the larst image in your trajectory as a starting point for the MLP MD
max_steps = 1000 #Maximum steps the MLP MD can take
min_steps = 1000 #Minimum steps the MLP MD can take
dump_step = 1 #How often you save trajectory points
print_step = 1 #How often you print predicted properties
num_uncertain = 1000 #Total number of trajectory points with a force uncertainty outside of the threshold before the MD is terminated
max_force_sd = 0.5 #Maxmimum force standard deviation(std). If the MLP MD gets higher force std the simualtion will stop
force_sd_threshold = 0.2 #Force std threshold for uncertain trajectory points

[simulate.NEB] #Main nugded elastic band(NEB) paramaters. Can be updated by each system
opt_steps = 200 #Maxmimum optimization steps of the initial/final image
opt_fmax = 0.05 #Minimum force for the structure optimization
neb_steps = 1000 #Maxmimum optimization steps of NEB
neb_fmax = 0.05 #Minimum force for the NEB optimization
num_img = 5 #The number of intermidate images in the NEB
climb = false #Using climbing image or not
friction_MD = 0.003 #Friction constant of the little MD performed for the NEB images to get out-of-distribution samples
temperature_MD = 1500 
time_MD = 1
time_step_MD = 1
print_step = 1
device = 'cpu'

# Here we list the 5 systems used in this workflow (NaCoPO4,NaMnPO4,NaNiPO4,NaFePO4 and NaFePO4_NEB)
[simulate.runs.NaCoPO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaCoPO4.traj' #CHANGE to correct path. System path

[simulate.runs.NaFePO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaFePO4.traj' #CHANGE to correct path. System path

[simulate.runs.NaMnPO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaMnPO4.traj' #CHANGE to correct path. System path

[simulate.runs.NaNiPO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaNiPO4.traj' #CHANGE to correct path. System path

[simulate.runs.NaFePO4_NEB]
method = 'NEB'
initial_image = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaFePO4_init.traj' #CHANGE to correct path. System path
final_image = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaFePO4_final.traj' #CHANGE to correct path. System path

### 3) Select step ###
[select]
train_set = '/home/energy/mahpe/Published_code/polyanion_cathode_dataset/Combined.xyz' ##CHANGE to correct path. System path
kernel = "full-g" #Kernel for which the features are mapped into
selection = "lcmd_greedy" #The selection method
n_random_features = 500 #Number of random features
batch_size = 10 #IMPORTANT. Number of structure you want to label in the next step
device = 'cpu'

[select.runs.NaCoPO4]
method= 'MD' 

[select.runs.NaFePO4]
method= 'MD' 

[select.runs.NaMnPO4]
method= 'MD' 

[select.runs.NaNiPO4]
method= 'MD' 

[select.runs.NaFePO4_NEB]
method= 'NEB' 

### 4) Labeling step ###
[labeling] 
train_set = '/home/energy/mahpe/Published_code/polyanion_cathode_dataset/Combined.xyz' #CHANGE to correct path. Training set datapath.
method='VASP'

[labeling.runs.NaCoPO4]
nupdown = 48
ldau_luj = {'Co'= {'L'= 2, 'U'= 3.32, 'J'= 0}}

[labeling.runs.NaFePO4]
nupdown = 64
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}}

[labeling.runs.NaMnPO4]
nupdown = 80
ldau_luj = {'Mn'= {'L'= 2, 'U'= 3.9, 'J'= 0}}

[labeling.runs.NaNiPO4]
nupdown = 32
ldau_luj = {'Ni'= {'L'= 2, 'U'= 6.2, 'J'= 0}}

[labeling.runs.NaFePO4_NEB]
nupdown = 64
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}}

[labeling.VASP]
xc = 'PBE'
encut = 520
sigma = 0.05
ediff = 1e-06
ediffg = -0.02
algo = 'all'
prec = 'accurate'
ibrion = 2
isif = 3
ismear = 0
ispin = 2
nelmin = 8
nelm = 400
lmaxmix = 4
nsw = 1
lorbit = 12
ncore = 8
lcharg = true
lreal = 'auto'
ldau = true
gamma = true
lwave = false
istart = 0
isym = 0
symprec = 1e-7
lasph=true
time = 0.05
command = 'mpirun vasp_std'
setups = 'materialsproject'
kpts = [ 3, 2, 3,]
nupdown = 20 #This is an example of a dummy parameter which will change in the label step depending on the system
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}} #This is an example of a dummy parameter which will change in the label step depending on the system

[labeling.GPAW]
xc='PBE'
mode= {name='pw',ecut=520}
eigensolver= {name='dav',niter=1}
occupations= {name='fermi-dirac',width=0.05,fixmagmom=true}
#mode.name='pw'
#mode.ecut=520
#eigensolver.name='dav'
#eigensolver.niter=1
#occupations.name='fermi-dirac'
#occupations.width=0.05
#occupations.fixmagmom=true
#convergence.energy=1e-05
#convergence.density=1
#convergence.eigenstates=1
maxiter=200
kpts = [3,2,2]