[global]
run_path = '/home/energy/mahpe/Published_code/autocPaiNN/Example'
random_seed = 3407
max_iteration = 10

[train]
cutoff = 4.0
val_ratio = 0.1
node_size = 64 
num_interactions = 4
output_dir = 'model_output'
dataset = '/home/energy/mahpe/Published_code/polyanion_cathode_dataset/Combined.xyz'
max_steps = 1500000
batch_size = 20
initial_lr = 0.0001
forces_weight = 0.98
charge_weight = 0.1
stress_weight = 1000
log_interval = 2000

plateau_scheduler = true
normalization = true 
atomwise_normalization = true 
stop_patience = 1000

random_seed = 0
compute_forces = true
compute_stress = true
compute_magmom=true
compute_bader_charge=true

stop_after_train = false
load_prev_iter_model = true

[train.ensemble]
128_node_4_layer = {node_size = 128, num_interactions = 4}
256_node_4_layer = {node_size = 256, num_interactions = 4}
512_node_4_layer = {node_size = 512, num_interactions = 4}

[simulate.MD]
time_step = 1
temperature = 1000
device = 'cpu'
start_indice = -1
max_steps = 100
min_steps = 1000
dump_step = 1
print_step = 1
num_uncertain = 1000
max_force_sd = 0.5
force_sd_threshold = 0.2

[simulate.NEB]
opt_steps = 200
opt_fmax = 0.05
neb_fmax = 0.05
neb_steps = 1000
num_img = 5
climb = false
friction_MD = 0.003
temperature_MD = 1500
time_MD = 1
time_step_MD = 1
print_step = 1
device = 'cpu'

[simulate.runs.NaCoPO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaCoPO4.traj'

[simulate.runs.NaFePO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaFePO4.traj'

[simulate.runs.NaMnPO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaMnPO4.traj'

[simulate.runs.NaNiPO4]
method = 'MD'
init_traj = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaNiPO4.traj'

[simulate.runs.NaFePO4_NEB]
method = 'NEB'
initial_image = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaFePO4_init.traj'
final_image = '/home/energy/mahpe/Published_code/autocPaiNN/Example_data/NaFePO4_final.traj'

[select]
train_set = '/home/energy/mahpe/Published_code/polyanion_cathode_dataset/Combined.xyz' 
kernel = "full-g"
selection = "lcmd_greedy"
n_random_features = 500
batch_size = 10
device = 'cpu'

[select.runs.NaCoPO4]
method= 'MD' 

[select.runs.NaFePO4]
method= 'MD' 

[select.runs.NaMnPO4]
method= 'MD' 

[select.runs.NaNiPO4]
method= 'MD' 

[select.runs.NaFePO4_NEB]
method= 'NEB' 

[labeling] 
train_set = '/home/energy/mahpe/Published_code/polyanion_cathode_dataset/Combined.xyz' 
method='VASP'

[labeling.runs.NaCoPO4]
nupdown = 48
ldau_luj = {'Co'= {'L'= 2, 'U'= 3.32, 'J'= 0}}

[labeling.runs.NaFePO4]
nupdown = 64
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}}

[labeling.runs.NaMnPO4]
nupdown = 80
ldau_luj = {'Mn'= {'L'= 2, 'U'= 3.9, 'J'= 0}}

[labeling.runs.NaNiPO4]
nupdown = 32
ldau_luj = {'Ni'= {'L'= 2, 'U'= 6.2, 'J'= 0}}

[labeling.runs.NaFePO4_NEB]
nupdown = 64
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}}

[labeling.VASP]
xc = 'PBE'
encut = 520
sigma = 0.05
ediff = 1e-06
ediffg = -0.02
algo = 'all'
prec = 'accurate'
ibrion = 2
isif = 3
ismear = 0
ispin = 2
nelmin = 8
nelm = 400
lmaxmix = 4
nsw = 1
lorbit = 12
ncore = 8
lcharg = true
lreal = 'auto'
ldau = true
gamma = true
lwave = false
istart = 0
isym = 0
symprec = 1e-7
lasph=true
time = 0.05
command = 'mpirun vasp_std'
setups = 'materialsproject'
kpts = [ 3, 2, 3,]
nupdown = 20
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}}

[labeling.GPAW]
xc='PBE'
mode= {name='pw',ecut=520}
eigensolver= {name='dav',niter=1}
occupations= {name='fermi-dirac',width=0.05,fixmagmom=true}
#mode.name='pw'
#mode.ecut=520
#eigensolver.name='dav'
#eigensolver.niter=1
#occupations.name='fermi-dirac'
#occupations.width=0.05
#occupations.fixmagmom=true
#convergence.energy=1e-05
#convergence.density=1
#convergence.eigenstates=1
maxiter=200
kpts = [3,2,2]