[GPAW]
xc='PBE'
mode= {name='pw',ecut=520}
eigensolver= {name='dav',niter=1}
occupations= {name='fermi-dirac',width=0.05,fixmagmom=true}
#mode.name='pw'
#mode.ecut=520
#eigensolver.name='dav'
#eigensolver.niter=1
#occupations.name='fermi-dirac'
#occupations.width=0.05
#occupations.fixmagmom=true
#convergence.energy=1e-05
#convergence.density=1
#convergence.eigenstates=1
maxiter=200
kpts = [3,2,2]


[VASP]
xc = 'PBE'
encut = 520
sigma = 0.05
ediff = 1e-06
ediffg = -0.02
algo = 'all'
prec = 'accurate'
ibrion = 2
isif = 3
ismear = 0
ispin = 2
nelmin = 8
nelm = 400
lmaxmix = 4
nsw = 1
lorbit = 12
ncore = 8
lcharg = true
lreal = 'auto'
ldau = true
gamma = true
lwave = false
istart = 0
isym = 0
symprec = 1e-7
lasph=true
time = 0.05
command = 'mpirun vasp_std'
setups = 'materialsproject'
kpts = [ 3, 2, 3,]
nupdown = 20
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}}